# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ccad4d575b6d399b5ac6d5328bbc273507b2573ed3ab0cb632f88ef2ce38b1d6c03c84cb233b72f67c09adf199ad9ea7a2a09681428514cfafc6719d8608823
  paypal_host: https://www.sandbox.paypal.com
  app_host: https://b1cb101d.ngrok.io

test:
  secret_key_base: 5539d9617df7af74a8f97f0c3dc152149e73cdad8aa87ab268439913e4790b1470599595e29b321ad34dede94e9906dd5c3ddbbfd80f7e89322adc7d089b00c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://fmenu-test.co.jp/
